"""updated the schema and modal for the booking

Revision ID: 26bc848b0350
Revises: 9511dfd75501
Create Date: 2026-06-05 15:04:28.687318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26bc848b0350'
down_revision: Union[str, Sequence[str], None] = '9511dfd75501'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('required_capacity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'required_capacity')
    # ### end Alembic commands ###
