"""create bookings table

Revision ID: 2a55225c1480
Revises: 7b17fa67ba7d
Create Date: 2026-05-20 15:08:02.881339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a55225c1480'
down_revision: Union[str, Sequence[str], None] = '7b17fa67ba7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_name', sa.String(), nullable=False))
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('bookings', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)
    op.alter_column('bookings', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               nullable=False)
    op.drop_column('bookings', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('bookings', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('bookings', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('bookings', 'user_name')
    # ### end Alembic commands ###
