"""add date and reason to bookings

Revision ID: 527abd341448
Revises: 89f86778de38
Create Date: 2026-05-29 18:38:12.847987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "527abd341448"
down_revision: Union[str, Sequence[str], None] = "89f86778de38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("date", sa.Date(), nullable=True))
    op.add_column("bookings", sa.Column("reason", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bookings", "reason")
    op.drop_column("bookings", "date")
    # ### end Alembic commands ###
