"""update user model

Revision ID: 61455e96d191
Revises: 527abd341448
Create Date: 2026-06-01 14:00:25.533568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61455e96d191'
down_revision: Union[str, Sequence[str], None] = '527abd341448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bookings', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('bookings', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
