"""add user_id to bookings

Revision ID: 89f86778de38
Revises: 2a55225c1480
Create Date: 2026-05-25 21:53:26.435183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89f86778de38'
down_revision: Union[str, Sequence[str], None] = '2a55225c1480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['user_id'], ['id'])
    op.drop_column('bookings', 'user_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'user_id')
    # ### end Alembic commands ###
