"""replace user_id with user_name in bookings

Revision ID: 9511dfd75501
Revises: 61455e96d191
Create Date: 2026-06-03 19:58:00.232667

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9511dfd75501"
down_revision: Union[str, Sequence[str], None] = "61455e96d191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bookings", sa.Column("user_name", sa.String(), nullable=True))
    op.create_unique_constraint(None, "bookings", ["user_name"])
    op.drop_constraint(op.f("bookings_user_id_fkey"), "bookings", type_="foreignkey")
    op.drop_column("bookings", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bookings",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("bookings_user_id_fkey"), "bookings", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "bookings", type_="unique")
    op.drop_column("bookings", "user_name")
    # ### end Alembic commands ###
